"Filed out from Dolphin Smalltalk 7"!

ExternalStructure subclass: #DirectWriteStructure
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DirectWriteStructure guid: (GUID fromString: '{700de161-6c34-4612-8587-d38d960e6945}')!
DirectWriteStructure isAbstract: true!
DirectWriteStructure comment: ''!
!DirectWriteStructure categoriesForClass!External-Data-Structured! !
