"Filed out from Dolphin Smalltalk 7"!

ExternalStructure subclass: #Direct2dStructure
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Direct2dStructure guid: (GUID fromString: '{f7af963b-37b4-497c-8487-f46c1ca5de76}')!
Direct2dStructure isAbstract: true!
Direct2dStructure comment: ''!
!Direct2dStructure categoriesForClass!External-Data-Structured! !
