"Filed out from Dolphin Smalltalk 7"!

Object subclass: #IrInstruction
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
IrInstruction guid: (GUID fromString: '{8FC4B7EA-215C-4EBB-BC6A-E3331048B15D}')!
IrInstruction comment: 'Intermediate instruction that, along with subclasses, represents a logical abstraction of the operations supported by the VM without the details of the physical representation as bytecodes. Used to simplify code generation from a parse tree.'!
!IrInstruction categoriesForClass!System-Compiler! !
